version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/api
hooks:
  BeforeInstall:
    - location: /cd/afterInstall.sh
      runas: root
  ApplicationStart:
    - location: /cd/start.sh
      runas: root
  ValidateService:
    - location: /cd/healthCheck.sh
      runas: ubuntu
