version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/api
hooks:
  ApplicationStart:
    - location: /start.sh
      runas: root
  ValidateService:
    - location: /healthCheck.sh
      runas: ubuntu
