version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
      - pwd
    run-as: root
  build:
    commands:
      - npx @nestjs/cli build
      - rm -rf node_modules
    run-as: root
artifacts:
  files:
    - "**/*"
cache:
  paths:
    - "node_modules/**/*"