version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/api
hooks:
  BeforeInstall:
    - location: /initialize.sh
      runas: ubuntu

  ApplicationStart:
    - location: /start.sh
      runas: ubuntu
  ValidateService:
    - location: /healthCheck.sh
      runas: ubuntu
