version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/api
hooks:
  BeforeInstall:
    - location: /cd/initialize.sh
      runas: ubuntu

  AfterInstall:
    - location: /cd/start.sh
      runas: ubuntu
  ValidateService:
    - location: /cd/healthCheck.sh
      runas: ubuntu
